namespace DotrModdingTool2IMGUI;

public enum SearchMode
{
    Dragon = 0x00,
    Spellcaster = 0x01,
    Zombie = 0x02,
    Warrior = 0x03,
    BeastWarrior = 0x04,
    Beast = 0x05,
    WingedBeast = 0x06,
    Fiend = 0x07,
    Fairy = 0x08,
    Insect = 0x09,
    Dinosaur = 0x0A,
    Reptile = 0x0B,
    Fish = 0x0C,
    SeaSerpent = 0x0D,
    Machine = 0x0E,
    Thunder = 0x0F,
    Aqua = 0x10,
    Pyro = 0x11,
    Rock = 0x12,
    Plant = 0x13,
    LightAttributeMonsters = 0x14,
    DarkAttributeMonsters = 0x15,
    FireAttributeMonsters = 0x16,
    EarthAttributeMonsters = 0x17,
    WaterAttributeMonsters = 0x18,
    WindAttributeMonsters = 0x19,
    MaybeBattlingOpponent = 0x1a,
    MaybeSelf = 0x1b,
    CardNumberMatchesExtraData = 0x1C,
    Monsters = 0x1D,
    Spells = 0x1E,
    AllCards = 0x1F,
    CardWithWorstStats = 0x20,
    CardWithBestStats = 0x21,
    LeaderId = 0x22,
    MonstersWithAttackGreaterOrEqual = 0x24,
    MonstersWithAttackLessOrEqual = 0x25,
    LastPlayedCard = 0x2D,
    Graveyard = 0x2f,
    Random = 0x30,
    Female = 0x31,
    ChooseTarget = 0x33,
    AllCardsExceptLeaders = 0x34,
    CardsInAttackPosition = 0x35,
    FaceUpTraps = 0x36,
    DragonsWithAttackGreaterOrEqual = 0x37,
    LeaderKind =0x38,
    MonstersWithDefenseGreaterOrEqual = 0x39,
    MonstersWithDefenseLessOrEqual = 0x3A,
    Immortal = 0x3B,
    FaceDownCards = 0x3C,
    CurrentlyAttackCard_CurrentPos = 0x3D,
    DefaultOrAllTargets = 0x3F
}
